create table if not exists public.profiles (id uuid primary key references auth.users(id) on delete cascade, username text unique not null, display_name text, avatar_url text, created_at timestamptz default now());
create table if not exists public.messages (id bigint generated by default as identity primary key, conversation_id uuid not null, sender_id uuid references auth.users(id) on delete cascade not null, body text, attachment_url text, attachment_name text, created_at timestamptz default now());
create index if not exists messages_conversation_created on public.messages(conversation_id,created_at);
alter table public.profiles enable row level security;
alter table public.messages enable row level security;
create policy "profiles readable" on public.profiles for select to authenticated using (true);
create policy "own profile insert" on public.profiles for insert to authenticated with check (auth.uid()=id);
create policy "messages readable" on public.messages for select to authenticated using (true);
create policy "messages insert own" on public.messages for insert to authenticated with check (auth.uid()=sender_id);

insert into storage.buckets (id,name,public) values ('documents','documents',true) on conflict (id) do update set public=true;
create policy "documents read" on storage.objects for select to authenticated using (bucket_id='documents');
create policy "documents upload own folder" on storage.objects for insert to authenticated with check (bucket_id='documents' and (storage.foldername(name))[1]=auth.uid()::text);