import React,{useEffect,useState}from'react';
import{View,Text,TextInput,TouchableOpacity,FlatList,StyleSheet,Alert,Linking}from'react-native';
import{StatusBar}from'expo-status-bar';
import*as DocumentPicker from'expo-document-picker';
import{supabase}from'./src/lib/supabase';
import{sendMessage,subscribeToMessages}from'./src/services/chat';
import{uploadDocument}from'./src/services/storage';

const ROOM='00000000-0000-4000-8000-000000000003';

export default function App(){
 const[session,setSession]=useState(null),[loading,setLoading]=useState(true),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[authMode,setAuthMode]=useState('login');
 const[messages,setMessages]=useState([]),[text,setText]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{if(!supabase){setLoading(false);return;}supabase.auth.getSession().then(({data})=>{setSession(data.session);setLoading(false)});const{data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>data.subscription.unsubscribe()},[]);
 useEffect(()=>{if(!session||!supabase)return;let active=true;supabase.from('messages').select('*').eq('conversation_id',ROOM).order('created_at',{ascending:true}).limit(100).then(({data,error})=>{if(error)Alert.alert('Chat error',error.message);else if(active)setMessages(data||[])});const off=subscribeToMessages(ROOM,m=>setMessages(x=>x.some(v=>v.id===m.id)?x:[...x,m]));return()=>{active=false;off()};},[session]);
 const auth=async()=>{if(!supabase)return Alert.alert('Setup required','Add Supabase URL and publishable/anon key in the app environment.');if(!email||!password)return;setBusy(true);const r=authMode==='login'?await supabase.auth.signInWithPassword({email,password}):await supabase.auth.signUp({email,password});setBusy(false);if(r.error)Alert.alert('AJislive3',r.error.message);else if(authMode==='signup'&&!r.data.session)Alert.alert('Account created','Check your email to confirm, then login.');};
 const send=async()=>{if(!text.trim()||!session)return;setBusy(true);const r=await sendMessage({conversationId:ROOM,senderId:session.user.id,body:text.trim()});setBusy(false);if(r.error)Alert.alert('Send failed',r.error.message);else setText('')};
 const pick=async()=>{if(!session)return;const r=await DocumentPicker.getDocumentAsync({copyToCacheDirectory:true});if(r.canceled)return;setBusy(true);try{const file=r.assets[0];const up=await uploadDocument(file,session.user.id);const m=await sendMessage({conversationId:ROOM,senderId:session.user.id,body:'📎 '+file.name,attachment_url:up.url,attachment_name:file.name});if(m.error)throw m.error;}catch(e){Alert.alert('Upload failed',e.message)}finally{setBusy(false)}};
 const call=(kind)=>Alert.alert(kind+' Call','Live video/voice calling is ready for LiveKit integration. Add the LiveKit URL and a secure token endpoint to enable real calls.');
 if(loading)return <View style={s.center}><Text style={s.logo}>AJislive3</Text><Text style={s.muted}>Loading...</Text></View>;
 if(!session)return <View style={s.center}><Text style={s.logo}>AJislive3</Text><Text style={s.tag}>Chat • Video • Documents</Text><TextInput value={email}onChangeText={setEmail}placeholder="Email"placeholderTextColor="#888"autoCapitalize="none"keyboardType="email-address"style={s.authInput}/><TextInput value={password}onChangeText={setPassword}placeholder="Password"placeholderTextColor="#888"secureTextEntry style={s.authInput}/><TouchableOpacity onPress={auth}style={s.primary}><Text style={s.primaryText}>{busy?'Please wait...':authMode==='login'?'Login':'Create account'}</Text></TouchableOpacity><TouchableOpacity onPress={()=>setAuthMode(authMode==='login'?'signup':'login')}><Text style={s.link}>{authMode==='login'?'Create new account':'Back to login'}</Text></TouchableOpacity></View>;
 return <View style={s.root}><StatusBar style="light"/><View style={s.header}><View><Text style={s.logo}>AJislive3</Text><Text style={s.online}>● Online</Text></View><View style={s.actions}><TouchableOpacity onPress={()=>call('Video')}style={s.icon}><Text>📹</Text></TouchableOpacity><TouchableOpacity onPress={()=>call('Voice')}style={s.icon}><Text>📞</Text></TouchableOpacity><TouchableOpacity onPress={()=>supabase.auth.signOut()}style={s.icon}><Text>↪️</Text></TouchableOpacity></View></View><FlatList style={s.list}data={messages}keyExtractor={x=>String(x.id)}renderItem={({item})=><View style={s.msg}><Text style={s.name}>{item.sender_id===session.user.id?'You':'User'}</Text><Text style={s.body}>{item.body}</Text>{item.attachment_url&&<TouchableOpacity onPress={()=>Linking.openURL(item.attachment_url)}><Text style={s.file}>Open document: {item.attachment_name||'file'} ↗</Text></TouchableOpacity>}<Text style={s.time}>{new Date(item.created_at).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</Text></View>}/><View style={s.composer}><TouchableOpacity onPress={pick}style={s.attach}><Text style={s.attachText}>📎</Text></TouchableOpacity><TextInput value={text}onChangeText={setText}placeholder="Message..."placeholderTextColor="#888"style={s.input}onSubmitEditing={send}/><TouchableOpacity disabled={busy}onPress={send}style={s.send}><Text>➤</Text></TouchableOpacity></View></View>
}
const s=StyleSheet.create({root:{flex:1,backgroundColor:'#0b0f14'},center:{flex:1,backgroundColor:'#0b0f14',alignItems:'center',justifyContent:'center',padding:24},header:{height:90,padding:18,paddingTop:42,backgroundColor:'#121923',flexDirection:'row',justifyContent:'space-between',alignItems:'center'},logo:{fontSize:28,fontWeight:'800',color:'#fff'},tag:{color:'#ff8a00',marginBottom:24,marginTop:6},online:{fontSize:12,color:'#32d583'},muted:{color:'#888',marginTop:8},actions:{flexDirection:'row'},icon:{backgroundColor:'#202b38',padding:10,borderRadius:14,marginLeft:8},list:{padding:14},msg:{backgroundColor:'#17212b',padding:12,borderRadius:15,marginBottom:10,maxWidth:'88%'},name:{color:'#ff8a00',fontWeight:'700'},body:{color:'#fff',fontSize:16,marginTop:3},file:{color:'#5db7ff',marginTop:8},time:{color:'#718096',fontSize:10,marginTop:5},composer:{flexDirection:'row',alignItems:'center',padding:10,backgroundColor:'#121923'},attach:{padding:12},attachText:{fontSize:22},input:{flex:1,backgroundColor:'#202b38',color:'#fff',borderRadius:22,paddingHorizontal:16,paddingVertical:10},send:{backgroundColor:'#ff8a00',borderRadius:22,width:44,height:44,alignItems:'center',justifyContent:'center',marginLeft:8},authInput:{width:'100%',backgroundColor:'#202b38',color:'#fff',borderRadius:12,padding:14,marginTop:10},primary:{width:'100%',backgroundColor:'#ff8a00',padding:15,borderRadius:12,alignItems:'center',marginTop:16},primaryText:{fontWeight:'800',color:'#111'},link:{color:'#5db7ff',marginTop:18}});